### PR TITLE
Updated

### PR DESCRIPTION
**Pull request by pr-asadi**
1. Removed CWD variable
2. Replaced shebangs.

### CODE REVIEW

**Comment by MahdiMirzadeh** [comment]
Hello there, CWD is for future purposes:
$ git clone https://github.com/mahdymirzade/dumbash /opt/dumbash
$ /opt/dumbash/setup.sh

But $WORKING_DIR wasn't suitable.

**Comment by pr-asadi** [comment]
Hi.
```
$ bash ~/dumBash/setup.sh /home/USER/dumBash
```
The above command works properly.

If you run setup.sh in ~/dumBash directory, it will happen a problem. You can test that.
```
$ cd ~/dumBash
$ bash setup.sh
$ cat ~/.bashrc
```

**Comment by MahdiMirzadeh** [comment]
### EDIT: I didn't see the change of current WORKING_DIR variable which led me to a misunderstanding, I merged the commit.

great, but the problem is sth else, In this part:
```
printf "%s\n" "source ${WORKING_DIR}/dumBash.sh" >> ~/.zshrc
```
So, when the file in your PR executes, Like this:
```
$ bash setup.sh
```
the $WORKING_DIR/$CWD are:
```
$ WORKING_DIR: .
$ CWD: /home/mahdy/dumBash
```
This command of $WORKING_DIR will add this to the end of .bashrc:
```
source ./dumBash.sh
```
But we don't have anything named ~/dumBash.sh & we don't make a link from original file.

$CWD's purpose is to fix this issue by file's full path.

**Comment by pr-asadi** [comment]
No.
```
$ cd ~/dumBash
$ bash setup.sh
$ cat ~/.bashrc
  > source /home/USER/dumBash/dumBash.sh
```
and
```
$ bash ~/dumBash/setup.sh /home/USER/dumBash
$ cat ~/.bashrc
 > source /home/USER/dumbash/dumBash.sh
```
If path does not entered in argument, WORKING_DIR variable  will take the PWD's value.

**Pull request merged**
